<a href="https://colab.research.google.com/github/AyeshaAreej/Machine-Learning-Python-/blob/main/Intro_to_ML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- Markdown cell -->
# Introduction to Machine Learning Lab 1
This is the first lab where we will explore the basics of Google Colab and write our first Python
code!

In [ ]:
#Python Code Cell
print("Hello, Machine Learning World!")

Hello, Machine Learning World!


In [ ]:
#Exploring Colab Interface
#printing sum
a=5; b=3
print(a+b)

8


In [3]:
#Mounting Google Drive With Collab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
#Loading sample_data.csv from drive
import pandas as pd
#sample example
#data = pd.read_csv('/content/drive/MyDrive/datasets/sample_data.csv')
#Loading actual csv
data = pd.read_csv('/content/sample_data/mnist_test.csv')


#writing data to csv
!mkdir -p "/content/drive/MyDrive/datasets" #creating dataset directory as it gave error if we run below command before creating directory
data.to_csv('/content/drive/MyDrive/datasets/output_data.csv')

#Understanding Numpy

NumPy (Numerical
Python) — Is the foundation of most ML workflows, providing fast and efficient array
computations, vectorized operations, and an overall boost in speed.

Example
Suppose we have two arrays representing the heights and weights of individuals, and we want to
compute their body mass index (BMI). Instead of looping through each element, we can do it all at once
with NumPy.

Result:This simple vectorized operation will gives us the BMI of all individuals in one go, demonstrating how NumPy
makes code both faster and more readable.

In [10]:
import numpy as np

#initiallizing height and weights are arrays
heights = np.array([1.75, 1.80, 1.65]) #in meters
weights = np.array([65, 78, 50]) #in kgs

bmi = weights / heights ** 2
print(bmi)

[21.2244898  24.07407407 18.36547291]


#Connection to ML Concepts
NumPy's array
operations make it an ideal tool for handling the data and computations that drive ML

In [17]:
#Data Preprocessing: data needs to be cleaned,transformed and normalized before training ML models
#Numpy made these operations easy

#1-Normalizing dataset It involves subtracting the mean and dividing by the standard deviation:
data= np.array([[4.0, 5.0, 6.0, 8.0, 10.0]])
normalized_data = (data - np.mean(data)) / np.std(data)
print("Normalized data",normalized_data)


#2-Matrix Operations: Most ML models, like linear regression, decision trees, and neural networks, involve matrix multiplication
#NumPy handles this operation with ease. Dot product between two matrices (or arrays) can be done in one line:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("Dot product",result)

Normalized data [[-1.2070197  -0.74278135 -0.27854301  0.64993368  1.57841037]]
Dot product [[19 22]
 [43 50]]


#Matrix Operation use in Linear Regression

In Linear Regression, you calculate predictions using the equation:

**ŷ = X ⋅ β + b**

Where, 𝑋 is our data matrix (input features), 𝛽 is the weights (coefficients), 𝑏 is the bias.


In [18]:
X = np.array([[1,2],[3,4],[5,6]]) #features
beta=np.array([0.5,1.5])        #learning parameters
b=0.1                           #bias
y_pred=np.dot(X,beta)+b         #prediction
print(y_pred)

[ 3.6  7.6 11.6]


#Numpy Arrays

In [20]:
#3-Key Numpy Concepts

#Arrays vs Lists

#Lists: Python lists are versatile but not optimized for heavy numerical computations
#When adding two lists element-wise, we have to use a loop in Python:

list_a=[1,2,3]
list_b=[4,5,6]

result = [a + b for a, b in zip(list_a, list_b)]
print('Two lists sum with python lists',result)


#With NumPy, this can be done directly and faster:
import numpy as np

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

result = array_a + array_b
print('Two arrays sum with numpy array',result)

Two lists sum with python lists [5, 7, 9]
Two arrays sum with numpy array [5 7 9]


In [31]:
#Creating Numpy Arrays
#Several ways to create numpy arrays

#1-From Lists:The simplest way to create an array is by converting a Python list using np.array()
np.array([1, 2, 3, 4])


#2-Using np.zeros() and np.ones():These functions create arrays filled with zeros or ones, respectively.
#This is useful when initializing weights or creating matrices to test algorithms.
np.zeros((3,3))  # A 3x3 matrix of zeros
np.ones((2, 4))  # A 3x3 matrix of ones

print('Zeros Array')
print (np.zeros((3,3)))
print('Ones Array')
print (np.ones((2, 4)))

#3-

Zeros Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
